name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Create .env.production.local
        run: echo "${{ secrets.DOTENV }}" > .env.production.local
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          target: ${{ secrets.SCP_TARGET }}
          source: dist/**
          strip_components: 1
          rm: true
